apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: chirpstack
  namespace: chirpstack-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: chirpstack
  namespace: chirpstack-operator
spec:
  channel: stable-v0
  name: chirpstack-operator
  source: deepshore-catalog
  sourceNamespace: chirpstack-operator
  installPlanApproval: Automatic
  startingCSV: chirpstack-operator.v0.0.2
