name: Build and publish container images on tag

on:
  push:
    branches:
      - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY_URL: quay.io
  ORG: maltegroth
  REPO_IMAGE: deepshore-catalog

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

    #   - name: Set up QEMU
    #     uses: docker/setup-qemu-action@v3

      - name: Download and install opm
        run: |
          set -ue
          set -o pipefail
          curl -sLf --retry 3 \
            -o /tmp/linux-amd64-opm \
            https://github.com/operator-framework/operator-registry/releases/download/v1.31.0/linux-amd64-opm
          sudo install -m 0755 /tmp/linux-amd64-opm /usr/local/bin/opm

      - name: Generate catalog
        run: make generate-catalog

      - name: Validate catalog
        run: make validate-catalog

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build and push operator image
        run: make docker-build docker-push
        env:
          DOCKER_IMAGE: ${{ env.REGISTRY_URL }}/${{ env.ORG }}/${{ env.REPO_IMAGE }}:latest
  